#!/bin/bash
#GABUT
clear
blue='\033[34;1m'
green='\033[32;1m'
purple='\033[35;1m'
cyan='\033[36;1m'
red='\033[31;1m'
white='\033[37;1m'
yellow='\033[33;1m'
clear
echo "TOOLS GABUTAN "
echo "[1].DDOS SERVER "
echo "[2].HACK SATELIT"
echo "[3].VIRTEX KEBAL "
echo "[4].BUG CHAT WA "
echo "[5].brechead from mod "

echo "\033[33;1m"
read -p "  SILAKAN PILIH YA SESUAI NOMOR  " c;

if [ $c = 1 ]
then
clear
echo " 😂😂😂😂😂"
xdg-open  "https://535f3715e873a3d8ccaabb87664691ed.serveo.net"
echo " 😂😂😂😂😂"

fi


if [ $c = 2 ]
then 
echo " 😂😂😂😂😂"
xdg-open  "https://535f3715e873a3d8ccaabb87664691ed.serveo.net"
echo " 😂😂😂😂😂"
fi
if [ $c = 3 ]
then 
echo " 😂😂😂😂😂"
xdg-open  "https://535f3715e873a3d8ccaabb87664691ed.serveo.net"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
fi
if [ $c = 4 ]
then 
echo " 😂😂😂😂😂"
xdg-open  "https://535f3715e873a3d8ccaabb87664691ed.serveo.net"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
fi
if [ $c = 5 ]
then 

xdg-open  "https://535f3715e873a3d8ccaabb87664691ed.serveo.net"
xdg-open  "https://535f3715e873a3d8ccaabb87664691ed.serveo.net"
xdg-open  "https://535f3715e873a3d8ccaabb87664691ed.serveo.net"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"
echo " 😂😂😂😂😂"


fi
